# string reconnector workflow
name: reconnector

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch

inputs:
  string:
    description: 'New string'
    required: true
    default: 'N/A'
  connector:
    description: 'Connector'
    required: true
    default: '+'
  filename:
    description: "Filename"
    required: true
    default: "dummy.txt"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  addLine:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #container: rocker/verse
    container: python:3.8
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: |
          git config --local user.email "rafael.flachar@gmail.com"
          git config --local user.name "G-You"
          python3 dummy.py -s {inputs.string} -c {inputs.connector} -f {inputs.filename}
      - run: |-
          git add dummy.txt
          git commit -m 'appended strings'
          git push 